/**
 * Portfolio projects. Set `github` / `live` to full URLs when ready.
 * Use `image` for a screenshot: place file in public/projects/ and set e.g. "/projects/my-app.png"
 */
export const projects = [
  {
    id: "elemental-puzzle",
    title: "Elemental Puzzle Game",
    tech: ["C++", "OOP"],
    highlights: [
      "Puzzle game with elemental forces (Air, Water, Fire, Earth)",
      "Random puzzle question system",
      "Achievements and leaderboards",
      "Modular puzzle engine for easy expansion",
    ],
    accent: "from-violet-500/30 to-cyan-500/20",
    image: "/projects/Elemental Puzzle Game.png",
    github: "https://github.com/NatsuDragneelX",
    live: "",
  },
  {
    id: "pc-builder",
    title: "Custom PC Builder Web App",
    tech: ["HTML", "CSS", "JavaScript", "Bootstrap", "Backend"],
    highlights: [
      "Build custom PCs with compatibility checks",
      "Real-time pricing",
      "User login and saved builds",
      "Fully responsive UI",
    ],
    accent: "from-emerald-500/30 to-teal-500/20",
    image: "/projects/Custom PC Builder Web App.png",
    github: "https://github.com/NatsuDragneelX",
    live: "",
  },
  {
    id: "manga-tracker",
    title: "MangaTracker",
    tech: ["Python", "Flask", "AniList API"],
    highlights: [
      "Local web app: upload a .txt list of manga titles and chapter numbers",
      "Matches entries against AniList so metadata stays accurate and consistent",
      "Review and confirm the right series when results are ambiguous",
      "Persists your library locally and keeps reading progress in sync",
    ],
    accent: "from-fuchsia-500/25 to-indigo-500/25",
    image: "/projects/MangaTracker.png",
    github: "https://github.com/NatsuDragneelX",
    live: "",
  },
  {
    id: "neuron-sim",
    title: "Neuron Simulation Tool",
    tech: ["Python", "NumPy", "Matplotlib"],
    highlights: [
      "Simulates neuron membrane potentials",
      "Euler method for differential equations",
      "CLI tool with configurable parameters",
      "Graph visualization",
    ],
    accent: "from-amber-500/30 to-orange-500/20",
    image: "/projects/Neuron Simulation Tool.png",
    github: "https://github.com/NatsuDragneelX",
    live: "",
  },
  {
    id: "csc3380-calculator",
    title: "CSC 3380 — Advanced Calculator",
    tech: ["C++", "Parsing", "CLI"],
    highlights: [
      "Expression REPL with semicolon-terminated input (VS Code / terminal workflow)",
      "Arithmetic, variables, precedence, and parentheses",
      "Constants: π, e, τ, φ, √2, √3, i, recursive Fibonacci",
      "Functions: sqrt, exp, log — with divide-by-zero and domain errors",
    ],
    accent: "from-slate-500/35 to-blue-600/25",
    image: "/projects/CSC 3380 Advanced Calculator.png",
    github: "https://github.com/NatsuDragneelX/God-Slayer",
    live: "",
  },
  {
    id: "mineflayer-speedrun",
    title: "Mineflayer Speedrun Bot",
    tech: ["Node.js", "Mineflayer", "Mineflayer-pathfinder"],
    highlights: [
      "Automates early-game speedrun-style tasks: wood → stone → iron",
      "Crafting, smelting, and progression toward Nether / End goals",
      "Chat commands (e.g. start / stop) and configurable host/port",
      "Extensible base for combat, Nether navigation, and dragon fight logic",
    ],
    accent: "from-orange-600/30 to-amber-600/20",
    image: "/projects/Mineflayer Speedrun Bot.png",
    github: "https://github.com/NatsuDragneelX/Project-MCSR",
    live: "",
  },
  {
    id: "group-dbms",
    title: "Group Project — DBMS (yt_enterprise)",
    tech: ["Node.js", "MySQL", "REST API", "CRUD"],
    highlights: [
      "Backend API for a group DBMS course project with MySQL (`yt_enterprise` / dump workflows)",
      "Customer endpoints: list all and get by id (e.g. GET /customers, GET /customers/:id)",
      "Connection pooling and configurable host, user, password, database",
      "ER diagrams and SQL dumps in-repo for schema reference",
    ],
    accent: "from-blue-600/30 to-slate-600/20",
    image: "/projects/Group Project DBMS.png",
    github: "https://github.com/NatsuDragneelX/Group_project_dbms",
    live: "",
  },
];
